### ISSUE TITLE
Upgrade sass-embedded from 1.66.1 to 1.67.0 problem

### ISSUE THREAD

**Issue by vitalinfo** [ntkme/sass-embedded-host-ruby#154]
after upgrade to 1.67.0 get an error

```
SassC::SyntaxError - Error: Can't find stylesheet to import.
  ╷
1 │ @import "sassc-embedded-import:1";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  sassc-embedded-import:0 1:9                                                            @import

          /home/app/assets/stylesheets/application.scss 14:9  root stylesheet
            /home/vendor/bundle/ruby/3.2.0/gems/dartsass-ruby-3.0.1/lib/sassc/engine.rb:58:in `rescue in render'
            /home/vendor/bundle/ruby/3.2.0/gems/dartsass-ruby-3.0.1/lib/sassc/engine.rb:22:in `render'
            /home/vendor/bundle/ruby/3.2.0/gems/dartsass-sprockets-3.0.0/lib/sassc/rails/template.rb:40:in `block in call'
            /home/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/utils.rb:145:in `block in module_include'
            /home/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/utils.rb:130:in `synchronize'
            /home/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/utils.rb:130:in `module_include'
```

any ideas what could went wrong?

**Comment by ntkme** [comment]
First of all, https://github.com/tablecheck/dartsass-ruby is a fork my project https://github.com/ntkme/sassc-embedded-shim-ruby. You can read the story on [why the fork was created](https://github.com/sass/sassc-ruby/issues/220) and [my comment on it](https://github.com/sass/sassc-ruby/issues/220#issuecomment-1416158475):

> While it is nice to everyone else that you want to maintain an obsolete technology, promoting it as a permanent solution is just a step backward.

Tablecheck's CTO ignored my warning and jumped onto creating the fork. However, [he had no interest to maintain the fork by himself or by his company since the beginning](https://github.com/sass/sassc-ruby/issues/220#issuecomment-1416270142):

> To be clear: I don't actually want to maintain these gems, I would much prefer if someone else did it!

From my view, just don't fork if you cannot maintain it. - So, going back to this issue itself, it's because the fork you're using is unmaintained and falling behind upstream.

Good luck.
